
///
/// This file was automatically created, using WCell's CodeFileWriter
/// Date: 7/19/2010
///

namespace WCell.Constants.Factions
{
	public enum FactionReputationIndex 
	{
		None = 0,
		BootyBay = 1,
		GelkisClanCentaur = 2,
		MagramClanCentaur = 3,
		ThoriumBrotherhood = 4,
		Ravenholdt = 5,
		Syndicate = 6,
		Gadgetzan = 7,
		Ratchet = 9,
		SteamwheedleCartel = 10,
		Alliance = 11,
		Horde = 12,
		ArgentDawn = 13,
		Orgrimmar = 14,
		DarkspearTrolls = 15,
		ThunderBluff = 16,
		Undercity = 17,
		GnomereganExiles = 18,
		Stormwind = 19,
		Ironforge = 20,
		Darnassus = 21,
		WintersaberTrainers = 27,
		Everlook = 28,
		TimbermawHold = 35,
		CenarionCircle = 36,
		Thrallmar = 37,
		HonorHold = 38,
		TheShaTar = 39,
		StormpikeGuard = 40,
		FrostwolfClan = 41,
		HydraxianWaterlords = 42,
		ShenDralar = 44,
		SilverwingSentinels = 45,
		WarsongOutriders = 46,
		Exodar = 49,
		DarkmoonFaire = 50,
		ZandalarTribe = 51,
		TheDefilers = 52,
		TheLeagueOfArathor = 53,
		BroodOfNozdormu = 54,
		SilvermoonCity = 55,
		Tranquillien = 56,
		TheScaleOfTheSands = 57,
		TheAldor = 58,
		TheConsortium = 60,
		TheMagHar = 61,
		TheScryers = 62,
		TheVioletEye = 63,
		CenarionExpedition = 64,
		Sporeggar = 65,
		Kurenai = 66,
		KeepersOfTime = 67,
		LowerCity = 69,
		AshtongueDeathsworn = 70,
		Netherwing = 71,
		ShaTariSkyguard = 72,
		OgriLa = 73,
		ValianceExpedition = 74,
		HordeExpedition = 75,
		TheTaunka = 76,
		TheHandOfVengeance = 77,
		ExplorersLeague = 78,
		TheKaluAk = 79,
		ShatteredSunOffensive = 80,
		WarsongOffensive = 81,
		REUSE = 82,
		TheWyrmrestAccord = 83,
		KirinTor = 84,
		TestFaction1 = 85,
		TestFaction3 = 87,
		TheSilverCovenant = 90,
		KnightsOfTheEbonBlade = 91,
		FrenzyheartTribe = 92,
		TheOracles = 93,
		ArgentCrusade = 94,
		TheSonsOfHodir = 97,
		TheSunreavers = 98,
		TheAshenVerdict = 104,
		End
	}

}

