using System;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Security;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3031
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: CLSCompliantAttribute(true)]
[assembly: ComVisibleAttribute(false)]
[assembly: AssemblyTitleAttribute("Castle.DynamicProxy2 for Microsoft .NET Framework 2.0")]
[assembly: AssemblyDescriptionAttribute("Dynamic Proxy Generator for the CLR")]
[assembly: AssemblyCompanyAttribute("Castle Project")]
[assembly: AssemblyProductAttribute("Castle.DynamicProxy2")]
[assembly: AssemblyCopyrightAttribute("Copyright (c) 2004,2005,2006 Castle Project - http://www.castleproject.org")]
[assembly: AssemblyVersionAttribute("2.0.3.0")]
[assembly: AssemblyInformationalVersionAttribute("2.0.3.5224")]
[assembly: AssemblyFileVersionAttribute("2.0.3.5224")]
[assembly: AssemblyDelaySignAttribute(false)]
[assembly: AllowPartiallyTrustedCallersAttribute()]
