//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCell.RealmServer.Res {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WCell_RealmServer {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WCell_RealmServer() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WCell.RealmServer.Res.WCell.RealmServer", typeof(WCell_RealmServer).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An attempt was made to recycle an EntityId that is already recycled! EntityId: {0} EntityIdType:{1}.
        /// </summary>
        internal static string AlreadyRecycledEntityId {
            get {
                return ResourceManager.GetString("AlreadyRecycledEntityId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tried to authenticate the client before their account was loaded/initialized!.
        /// </summary>
        internal static string BadAuthenticationProcedure {
            get {
                return ResourceManager.GetString("BadAuthenticationProcedure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character EntityId {0} Account {1} tried to connect while already logged in.
        /// </summary>
        internal static string CharacterAlreadyConnected {
            get {
                return ResourceManager.GetString("CharacterAlreadyConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character EntityId {0} not found in Account {1}.
        /// </summary>
        internal static string CharacterNotFound {
            get {
                return ResourceManager.GetString("CharacterNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character null, could not register.
        /// </summary>
        internal static string CharacterNullRegister {
            get {
                return ResourceManager.GetString("CharacterNullRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character null, could not unregister.
        /// </summary>
        internal static string CharacterNullUnregister {
            get {
                return ResourceManager.GetString("CharacterNullUnregister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relation added successfully: Character=&apos;{0}&apos;({1}), RelatedCharacter=&apos;{2}&apos;({3}), RelationType={4}, RelationResult={5}.
        /// </summary>
        internal static string CharacterRelationAdded {
            get {
                return ResourceManager.GetString("CharacterRelationAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relation add failed: Character=&apos;{0}&apos;({1}), RelatedCharacter=&apos;{2}&apos;({3}), RelationType={4}, RelationResult={5}.
        /// </summary>
        internal static string CharacterRelationAddedFailed {
            get {
                return ResourceManager.GetString("CharacterRelationAddedFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relation removing succeeded: Character={0}, RelatedCharacter={1}, RelationType={2}, RelationResult={3}.
        /// </summary>
        internal static string CharacterRelationRemoved {
            get {
                return ResourceManager.GetString("CharacterRelationRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relation removing failed: Character={0}, RelatedCharacter={1}, RelationType={2}, RelationResult={3}.
        /// </summary>
        internal static string CharacterRelationRemoveFailed {
            get {
                return ResourceManager.GetString("CharacterRelationRemoveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loaded {0} character relations of character &apos;{1}&apos; from the DB..
        /// </summary>
        internal static string CharacterRelationsLoaded {
            get {
                return ResourceManager.GetString("CharacterRelationsLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading the character relations for player &apos;{0}&apos; from the DB ({1}).
        /// </summary>
        internal static string CharacterRelationsLoadFailed {
            get {
                return ResourceManager.GetString("CharacterRelationsLoadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unloaded {0} character relations of character &apos;{1}&apos;..
        /// </summary>
        internal static string CharacterRelationsUnloaded {
            get {
                return ResourceManager.GetString("CharacterRelationsUnloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relation validation failed: Character=&apos;{0}&apos;({1}), RelatedCharacter=&apos;{2}&apos;({3}), RelationType={4}, RelationResult={5}.
        /// </summary>
        internal static string CharacterRelationValidationFailed {
            get {
                return ResourceManager.GetString("CharacterRelationValidationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player &apos;{0}&apos; already logged in! Removing them from the online list!.
        /// </summary>
        internal static string CharacterStillLoggedIn {
            get {
                return ResourceManager.GetString("CharacterStillLoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command configuration changed; reloading!.
        /// </summary>
        internal static string CommandConfigChanged {
            get {
                return ResourceManager.GetString("CommandConfigChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The command manager failed to (re)start! Reason: failed to create the script environment!.
        /// </summary>
        internal static string CommandMgrCEFailed {
            get {
                return ResourceManager.GetString("CommandMgrCEFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The command manager failed to (re)start/stop! Reason: failed to destroy the existing script environment!.
        /// </summary>
        internal static string CommandMgrDEFailed {
            get {
                return ResourceManager.GetString("CommandMgrDEFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The command manager failed to (re)start! Reason: failed to load command script files!.
        /// </summary>
        internal static string CommandMgrLoadFailed {
            get {
                return ResourceManager.GetString("CommandMgrLoadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The command manager (re)started successfully!.
        /// </summary>
        internal static string CommandMgrStarted {
            get {
                return ResourceManager.GetString("CommandMgrStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The command manager stopped successfully!.
        /// </summary>
        internal static string CommandMgrStopped {
            get {
                return ResourceManager.GetString("CommandMgrStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified command module doesn&apos;t exist! Module: {0}.
        /// </summary>
        internal static string CommandModuleDoesntExist {
            get {
                return ResourceManager.GetString("CommandModuleDoesntExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An exception occured within the IPC device when trying to communicate with the AuthServer..
        /// </summary>
        internal static string CommunicationException {
            get {
                return ResourceManager.GetString("CommunicationException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a catastrophic database failure, server not started.
        /// </summary>
        internal static string DatabaseFailure {
            get {
                return ResourceManager.GetString("DatabaseFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The required DBC file, &apos;{0}&apos;, does not exist!.
        /// </summary>
        internal static string DBCFileDoesntExist {
            get {
                return ResourceManager.GetString("DBCFileDoesntExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load and parse the DBC file, &apos;{0}&apos;!.
        /// </summary>
        internal static string DBCLoadFailed {
            get {
                return ResourceManager.GetString("DBCLoadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packet received/parsed with erroneous length! Packet ID: {0:X4} Length given: {1}.
        /// </summary>
        internal static string ErroneousPacketReceived {
            get {
                return ResourceManager.GetString("ErroneousPacketReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to retrieve account &apos;{0}&apos; from the AuthServer!.
        /// </summary>
        internal static string FailedToRetrieveAccount {
            get {
                return ResourceManager.GetString("FailedToRetrieveAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A fatal, unhandled exception was encountered!.
        /// </summary>
        internal static string FatalUnhandledException {
            get {
                return ResourceManager.GetString("FatalUnhandledException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GameTables loaded in {0}ms.
        /// </summary>
        internal static string GameTablesLoaded {
            get {
                return ResourceManager.GetString("GameTablesLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loaded data for Guild &apos;{0}&apos; from the DB..
        /// </summary>
        internal static string GuildLoaded {
            get {
                return ResourceManager.GetString("GuildLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading the data for Guild with ID &apos;{0}&apos; from the DB..
        /// </summary>
        internal static string GuildLoadFailed {
            get {
                return ResourceManager.GetString("GuildLoadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unloaded Guild &apos;{0}&apos;..
        /// </summary>
        internal static string GuildUnload {
            get {
                return ResourceManager.GetString("GuildUnload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Handling packet &apos;{0}&apos; with size of {1} bytes..
        /// </summary>
        internal static string HandlingPacket {
            get {
                return ResourceManager.GetString("HandlingPacket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempt to rename a character not belonging to the client&apos;s account! GUID: &apos;{0}&apos; ({1}).
        /// </summary>
        internal static string IllegalRenameAttempt {
            get {
                return ResourceManager.GetString("IllegalRenameAttempt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An entity attempted to move to an invalid/non-existent region! Target region: {0} Entity: {1}.
        /// </summary>
        internal static string InvalidRegionMove {
            get {
                return ResourceManager.GetString("InvalidRegionMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IPC device failed to reconnect to the AuthServer. Is the AuthServer running?.
        /// </summary>
        internal static string IPCProxyCouldntReconnect {
            get {
                return ResourceManager.GetString("IPCProxyCouldntReconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IPC device disconnected from AuthServer!.
        /// </summary>
        internal static string IPCProxyDisconnected {
            get {
                return ResourceManager.GetString("IPCProxyDisconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IPC device failed to connect to the AuthServer because the AuthServer is probably not running. Retrying in {0} seconds....
        /// </summary>
        internal static string IPCProxyFailed {
            get {
                return ResourceManager.GetString("IPCProxyFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IPC device failed to connect to the AuthServer. Retrying in {0} seconds....
        /// </summary>
        internal static string IPCProxyFailedException {
            get {
                return ResourceManager.GetString("IPCProxyFailedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IPC device successfully reconnected to the AuthServer!.
        /// </summary>
        internal static string IPCProxyReconnected {
            get {
                return ResourceManager.GetString("IPCProxyReconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IPC device successfully connected to the AuthServer!.
        /// </summary>
        internal static string IPCProxySucceeded {
            get {
                return ResourceManager.GetString("IPCProxySucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player tried to delete a mail message that is not theirs; possible error or exploit attempt! Player name: {0}.
        /// </summary>
        internal static string MailNotOwnerDelete {
            get {
                return ResourceManager.GetString("MailNotOwnerDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail System Halted.
        /// </summary>
        internal static string MailSystemHalted {
            get {
                return ResourceManager.GetString("MailSystemHalted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail System Started.
        /// </summary>
        internal static string MailSystemLoaded {
            get {
                return ResourceManager.GetString("MailSystemLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting Mail System....
        /// </summary>
        internal static string MailSystemStart {
            get {
                return ResourceManager.GetString("MailSystemStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Halting Mail System....
        /// </summary>
        internal static string MailSystemStop {
            get {
                return ResourceManager.GetString("MailSystemStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} regions loaded in {1}ms.
        /// </summary>
        internal static string MapsLoaded {
            get {
                return ResourceManager.GetString("MapsLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find {0}: {1}.
        /// </summary>
        internal static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An exception occured while trying to handle packet! Packet ID: &apos;{0}&apos;.
        /// </summary>
        internal static string PacketHandleException {
            get {
                return ResourceManager.GetString("PacketHandleException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The packet ID was out of range. Possible encryption/decryption corruption..
        /// </summary>
        internal static string PacketIDOutOfRange {
            get {
                return ResourceManager.GetString("PacketIDOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packet reports a length bigger than the amount of data available! Packet ID: {0}, reported length: {1}, available length: {2}.
        /// </summary>
        internal static string PacketLengthMismatch {
            get {
                return ResourceManager.GetString("PacketLengthMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to parse packet properly! Given opcode: {0:X4}.
        /// </summary>
        internal static string PacketParseFailed {
            get {
                return ResourceManager.GetString("PacketParseFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partitioned and started {0} regions in {1}ms.
        /// </summary>
        internal static string PartitionStartComplete {
            get {
                return ResourceManager.GetString("PartitionStartComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region context required. Add a message to the region to ensure the action is performed within the Region&apos;s context: {0}.
        /// </summary>
        internal static string RegionContextNeeded {
            get {
                return ResourceManager.GetString("RegionContextNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region context prohibited. Make sure to NOT call this method from within the region context due to deadlock risks or blocking code: {0}.
        /// </summary>
        internal static string RegionContextProhibited {
            get {
                return ResourceManager.GetString("RegionContextProhibited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region {0} now running!.
        /// </summary>
        internal static string RegionStarted {
            get {
                return ResourceManager.GetString("RegionStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region {0} stopped!.
        /// </summary>
        internal static string RegionStopped {
            get {
                return ResourceManager.GetString("RegionStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region is calling method while updating. Make sure to NOT call this and similar methods while a Region is updating: {0}.
        /// </summary>
        internal static string RegionUpdating {
            get {
                return ResourceManager.GetString("RegionUpdating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registered all packet handlers!.
        /// </summary>
        internal static string RegisteredAllHandlers {
            get {
                return ResourceManager.GetString("RegisteredAllHandlers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registered handler for {0}() for &apos;{1}&apos;.
        /// </summary>
        internal static string RegisteredHandler {
            get {
                return ResourceManager.GetString("RegisteredHandler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trying to register RealmServer while RealmServer is not running..
        /// </summary>
        internal static string RegisterNotRunning {
            get {
                return ResourceManager.GetString("RegisterNotRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relation Manager started.
        /// </summary>
        internal static string RelationManagerStarted {
            get {
                return ResourceManager.GetString("RelationManagerStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relation Manager stopped.
        /// </summary>
        internal static string RelationManagerStopped {
            get {
                return ResourceManager.GetString("RelationManagerStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renaming character - original name: &apos;{0}&apos; new name: &apos;{1}&apos;.
        /// </summary>
        internal static string RenamingCharacter {
            get {
                return ResourceManager.GetString("RenamingCharacter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resetting the IPC connection to the AuthServer!.
        /// </summary>
        internal static string ResetIPCConnection {
            get {
                return ResourceManager.GetString("ResetIPCConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while getting script engine instance! Script engine: &apos;{0}&apos;.
        /// </summary>
        internal static string ScriptEngineRetrieveError {
            get {
                return ResourceManager.GetString("ScriptEngineRetrieveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception encountered during script execution! Script engine: &apos;{0}&apos; Module name: &apos;{1}&apos; Function name: &apos;{2}&apos; {3}Exception: {4}.
        /// </summary>
        internal static string ScriptExecutionError {
            get {
                return ResourceManager.GetString("ScriptExecutionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load script: {0}!.
        /// </summary>
        internal static string ScriptLoadFailed {
            get {
                return ResourceManager.GetString("ScriptLoadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending packet &apos;{0}&apos; with a length of {1}.
        /// </summary>
        internal static string SendingPacket {
            get {
                return ResourceManager.GetString("SendingPacket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An exception was caught when trying to bind to the listening address! Make sure to check your configuration and verify that the host address and port are valid for this computer..
        /// </summary>
        internal static string ServerBaseStartExCaught {
            get {
                return ResourceManager.GetString("ServerBaseStartExCaught", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load the server ruleset for the given server type: {0}.
        /// </summary>
        internal static string ServerRulesetLoadFailed {
            get {
                return ResourceManager.GetString("ServerRulesetLoadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting up realm server..
        /// </summary>
        internal static string StartingServer {
            get {
                return ResourceManager.GetString("StartingServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting/initializing: {0}.
        /// </summary>
        internal static string StartInit {
            get {
                return ResourceManager.GetString("StartInit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception occured when starting/initializing: {0}.
        /// </summary>
        internal static string StartInitException {
            get {
                return ResourceManager.GetString("StartInitException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopping/cleaning up: {0}.
        /// </summary>
        internal static string StopCleanup {
            get {
                return ResourceManager.GetString("StopCleanup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception occured when stopping/cleaning up: {0}.
        /// </summary>
        internal static string StopCleanupException {
            get {
                return ResourceManager.GetString("StopCleanupException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The world manager failed to start!.
        /// </summary>
        internal static string WorldMgrFailed {
            get {
                return ResourceManager.GetString("WorldMgrFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The world manager started successfully!.
        /// </summary>
        internal static string WorldMgrSucceeded {
            get {
                return ResourceManager.GetString("WorldMgrSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} zones loaded in {1}ms.
        /// </summary>
        internal static string ZonesLoaded {
            get {
                return ResourceManager.GetString("ZonesLoaded", resourceCulture);
            }
        }
    }
}